services:
  - type: web
    name: food-recommendation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GOOGLE_API_KEY
        sync: false  # You'll set this in the Render dashboard 